#!/bin/bash

re='^[0-9]+$'

interpreterDir="/usr/local/bin/hexagony/interpreter.rb"

if [ -z ${1+x} ]; then
	echo "No file input"
	exit -1
elif [[ $1 =~ $re ]] ; then
	ruby $interpreterDir -g $1 > $2
	exit 0
fi

if [ $1 == "-d" ]; then
	ruby $interpreterDir -d $1
fi
if [ -d "/usr/local/bin/hexagony" ]; then
	ruby $interpreterDir $1
else
	echo "Could not locate /usr/local/bin/hexagony"
        exit -1
fi
